Debug Build Support
Moo-Ack-Productions/MCprep pull request #605
Opened 2024-07-21 18:23 UTC by StandingPadAnimations

This adds the ability to create a build of MCprep that can then be debugged using a debugger. Under the hood, this uses Microsoft's [debugpy](https://github.com/microsoft/debugpy) library, which is then installed into the Blender environment using the new wheels system introduced with Extensions (support for which has also been added).

This has been tested with VScode, but in theory should be editor agnostic. Some notes to be aware of:
- MCprep must be manually installed as a debug build, because installing extensions isn't supported in BpyBuild yet
- When using a debugger, the editor must be opened in the directory of the installed extension (ex. `~/.config/blender/4.2/extensions/user_default/mcprep/`). Hopefully we can get this ironed out by either including some configs or having the `debug` action generate them on the fly.
- Additional configuration might be required. For example, with VScode, the following configuration needs to be used:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Remote Attach",
            "type": "debugpy",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ]
        }
    ]
}
```
- This is not yet documented as it's a pretty advanced development feature, there really isn't an easy way to document it (especially as something editor agnostic)

Closes #604

2024-07-25 15:55 UTC, TheDuckCow commented
Just glancing through, I see this also represents embracing the new extension format. I gather that would mean needing to distribute two versions of MCprep right, one in extension format and one as a legacy addon?

2024-07-25 17:00 UTC, StandingPadAnimations commented
We could if we want to, or we could keep using only legacy builds for production. For simplicity, we should just distribute legacy builds, but make sure extension builds keep working for debug build support or for users that want to build an extension instead.

2024-08-14 19:03 UTC, TheDuckCow requested changes
Main reason for requesting change is to see if I can get the extension build to properly install the debuggy wheel. Same thing happens in 4.2 and 4.3, whether dragging and dropping to install the extension, navigating manually; and same popup appears when trying to manually enable the extension's addon after the extension is installed.

Other points are less important, figure we'd want to make sure this works cross platform, even though I personally probably won't end up using it much.

2024-08-14 19:08 UTC, StandingPadAnimations commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
This was automatically generated by VScode, I think VScode config files are just weird with supported JSON features

2024-08-14 19:10 UTC, StandingPadAnimations commented on action-scripts/build-patches/debug-mode.diff
> ++
Strange, the macOS wheel should be universal across both Intel and Silicon. I'll take a look at the action

2024-08-14 19:11 UTC, TheDuckCow commented
(Also, while not related to the v3.6.1 release, could be nice to merge by then I'd say since this seems pretty close otherwise)

2024-08-14 19:12 UTC, StandingPadAnimations commented on action-scripts/debug-build.py
There are plans for BpyBuild to handle extensions properly (already implemented technically, but some things still need to be finished, such as building legacy addons and extensions at the same time). Compatibility minimums would be something interesting to add for 0.5

2024-08-18 23:24 UTC, TheDuckCow approved these changes
Approved based on the wheel change we did for osx, knowing we might go a bit further in the future (I won't be using this mode in the meantime anyways)

2024-08-18 23:25 UTC, merged